twilio:
  account_sid: ${ACCOUNT_SID} #your account sid
  auth_token: ${AUTH_TOKEN} #your auth token
  trial_number: ${TRIAL_NUMBER} # your trial number
server:
  port: 8081
weather_app:
  url: ${WEATHER_APP_URL}
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: messager
  security:
    user:
      name: ${ADMIN}
      password: ${ADMIN_PASSWORD}